version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      RABBITMQ_NODENAME: ${RABBITMQ_NODENAME}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

networks:
  rabbitmq_go_net:
    driver: bridge
